name: "Backend: Build"

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    outputs:
      store-path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.3.0
          run_install: false

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: node_modules
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: |
            backend-${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

#      - name: Run linter check
#        run: pnpm lint

      - name: Check if app builds properly
        run: pnpm build

#      - name: Run tests with coverage
#        run: pnpm test:ci

#      - name: Generate coverage badges
#        uses: jpb06/coverage-badges-action@latest
#        with:
#          branches: main
#          coverage-summary-path: ./coverage/coverage-summary.json
#          commit-message: "ci(bot): Update coverage badges"
#          badges-icon: jest